// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Project_ERP.Models;

public partial class Account
{
    [Required]
    [StringLength(50)]
    public string AccountNumber { get; set; }

    [Required]
    [StringLength(100)]
    public string AccountNameAr { get; set; }

    [StringLength(100)]
    public string AccountNameEn { get; set; }

    public int? BranchID { get; set; }

    [Key]
    public int AccountID { get; set; }

    [ForeignKey("BranchID")]
    [InverseProperty("Accounts")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("Account")]
    public virtual ICollection<JVDetail> JVDetails { get; set; } = new List<JVDetail>();

    [InverseProperty("Account")]
    public virtual ICollection<SubAccounts_Detail> SubAccounts_Details { get; set; } = new List<SubAccounts_Detail>();
}