// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Project_ERP.Models;

public partial class Branch
{
    [Required]
    [StringLength(50)]
    public string BranchCode { get; set; }

    [Required]
    [StringLength(50)]
    public string BranchNameAr { get; set; }

    [StringLength(50)]
    public string BranchNameEn { get; set; }

    [Key]
    public int BranchID { get; set; }

    [InverseProperty("Branch")]
    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();

    [InverseProperty("Branch")]
    public virtual ICollection<City> Cities { get; set; } = new List<City>();

    [InverseProperty("Branch")]
    public virtual ICollection<JVDetail> JVDetails { get; set; } = new List<JVDetail>();

    [InverseProperty("Branch")]
    public virtual ICollection<JVType> JVTypes { get; set; } = new List<JVType>();

    [InverseProperty("Branch")]
    public virtual ICollection<JV> JVs { get; set; } = new List<JV>();

    [InverseProperty("Branch")]
    public virtual ICollection<SubAccount> SubAccounts { get; set; } = new List<SubAccount>();

    [InverseProperty("Branch")]
    public virtual ICollection<SubAccountsClient> SubAccountsClients { get; set; } = new List<SubAccountsClient>();

    [InverseProperty("Branch")]
    public virtual ICollection<SubAccounts_Detail> SubAccounts_Details { get; set; } = new List<SubAccounts_Detail>();

    [InverseProperty("Branch")]
    public virtual ICollection<SubAccounts_Level> SubAccounts_Levels { get; set; } = new List<SubAccounts_Level>();
}