// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Project_ERP.Models;

public partial class City
{
    [StringLength(50)]
    public string CityCode { get; set; }

    [StringLength(100)]
    public string CityNameAr { get; set; }

    [StringLength(100)]
    public string CityNameEn { get; set; }

    public int? BranchID { get; set; }

    [Key]
    public int CityID { get; set; }

    [ForeignKey("BranchID")]
    [InverseProperty("Cities")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<SubAccountsClient> SubAccountsClients { get; set; } = new List<SubAccountsClient>();
}