// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Project_ERP.Models;

public partial class JVType
{
    [Required]
    [StringLength(100)]
    public string JVTypeNameAr { get; set; }

    [StringLength(100)]
    public string JVTypeNameEn { get; set; }

    public int? BranchID { get; set; }

    [Key]
    public int JVTypeID { get; set; }

    [ForeignKey("BranchID")]
    [InverseProperty("JVTypes")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("JVType")]
    public virtual ICollection<JV> JVs { get; set; } = new List<JV>();
}