// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Project_ERP.Models;

[Table("SubAccountsClient")]
public partial class SubAccountsClient
{
    [Required]
    [StringLength(50)]
    public string ClientNo { get; set; }

    public int SubAccountID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BirthDate { get; set; }

    public int? CityID { get; set; }

    [Column(TypeName = "numeric(18, 8)")]
    public decimal? CreditLimit { get; set; }

    public bool IsDiscountTax { get; set; }

    public bool IsActive { get; set; }

    [StringLength(500)]
    public string Notes { get; set; }

    public int? BranchID { get; set; }

    [Key]
    public int ClientID { get; set; }

    [ForeignKey("BranchID")]
    [InverseProperty("SubAccountsClients")]
    public virtual Branch Branch { get; set; }

    [ForeignKey("CityID")]
    [InverseProperty("SubAccountsClients")]
    public virtual City City { get; set; }

    [ForeignKey("SubAccountID")]
    [InverseProperty("SubAccountsClients")]
    public virtual SubAccount SubAccount { get; set; }
}