// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Project_ERP.Models;

public partial class SubAccountsType
{
    [Required]
    [StringLength(100)]
    public string SubAccountTypeNameAr { get; set; }

    [StringLength(100)]
    public string SubAccountTypeNameEn { get; set; }

    public int? BranchID { get; set; }

    [Key]
    public int SubAccountTypeID { get; set; }

    [InverseProperty("SubAccountType")]
    public virtual ICollection<SubAccount> SubAccounts { get; set; } = new List<SubAccount>();
}