// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Project_ERP.Models;

public partial class SubAccount
{
    [Required]
    [StringLength(50)]
    public string SubAccountNumber { get; set; }

    [Required]
    [StringLength(100)]
    public string SubAccountNameAr { get; set; }

    [StringLength(100)]
    public string SubAccountNameEn { get; set; }

    public int? ParentID { get; set; }

    public bool IsMain { get; set; }

    public int LevelID { get; set; }

    public int? SubAccountTypeID { get; set; }

    public int? BranchID { get; set; }

    [Key]
    public int SubAccountID { get; set; }

    [ForeignKey("BranchID")]
    [InverseProperty("SubAccounts")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("Parent")]
    public virtual ICollection<SubAccount> InverseParent { get; set; } = new List<SubAccount>();

    [InverseProperty("SubAccount")]
    public virtual ICollection<JVDetail> JVDetails { get; set; } = new List<JVDetail>();

    [ForeignKey("LevelID")]
    [InverseProperty("SubAccounts")]
    public virtual SubAccounts_Level Level { get; set; }

    [ForeignKey("ParentID")]
    [InverseProperty("InverseParent")]
    public virtual SubAccount Parent { get; set; }

    [ForeignKey("SubAccountTypeID")]
    [InverseProperty("SubAccounts")]
    public virtual SubAccountsType SubAccountType { get; set; }

    [InverseProperty("SubAccount")]
    public virtual ICollection<SubAccountsClient> SubAccountsClients { get; set; } = new List<SubAccountsClient>();

    [InverseProperty("SubAccount")]
    public virtual ICollection<SubAccounts_Detail> SubAccounts_Details { get; set; } = new List<SubAccounts_Detail>();
}